openapi: "3.0.1"
info:
  title: Users Service API
  description: Users Microservice of Message in a Bottle Application
  version: "0.1"

servers:
  - url: /

paths:
  /block:
    post:
      summary: Block a user 
      tags:
        - Blacklist
      operationId: mib.resources.blacklist.block
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlockUser'
      responses:
        201:
          description: User correctly blocked
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: "It can be failure or success"
                  description:
                    type: string
                    description: "Human readable result"
                  blockItem:
                    $ref : '#/components/schemas/BlockItem'
        500:
          description: Failure in adding the user to blacklist
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: "It can be failure or success"
                  description:
                    type: string
                    description: "Human readable result"
          
        default:
          description: Error blocking the user

  /unblock:
    delete:
      summary: Unblocking a user 
      tags:
        - Blacklist
      operationId: mib.resources.blacklist.unblock
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlockUser'
      responses:
        202:
          description: User correctly unblocked
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: "It can be failure or success"
                  description:
                    type: string
                    description: "Human readable result"
                  blockItem:
                    $ref : '#/components/schemas/BlockItem'
        404:
          description: Not found blacklist instance
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: "It can be failure or success"
                  description:
                    type: string
                    description: "Human readable result"
          
        default:
          description: Error unblocking the user
  
  /blacklist:
      get:
        tags: [ Blacklist ]
        summary: Get a list of blocked and blocking users
        operationId: mib.resources.blacklist.get_blacklist
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequesterID'
        responses:
          200:
            description: Return a list of blocked and blocking users
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                      description: "It can be failure or success"
                    description:
                      type: string
                      description: "Human readable result"
                    blocking:
                      type: array
                      items: 
                        type: integer
                    blocked:
                      type: array
                      items: 
                        type: integer

          500:
            description: Internal error while retrieving
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                      description: "It can be failure or success"
                    description:
                      type: string
                      description: "Human readable result"

          default:
            description: An error occured while retrieving the blacklist

components:
  schemas:
    BlockUser:
      required:
        - requester_id
        - blocked_user_id
      type: object
      properties:
        requester_id:
          type: integer
          format: int64
          description: user ID of blocking user
          example: 1
        blocked_user_id:
          type: integer
          format: int64
          description: The id of blocked user
          example: 2
    
    BlockItem:
      required:
        - blocking_user_id
        - blocked_user_id
      type: object
      properties:
        blocking_user_id:
          type: integer
          format: int64
          description: The id of blocking user
          example: 1
        blocked_user_id:
          type: integer
          format: int64
          description: The id of blocked user
          example: 2

    RequesterID:
      required:
        - requester_id
      type: object
      properties:
        requester_id:
          type: integer
          format: int64
          description: user ID
          example: 123